version: '3'

services:
  gndjango.web:
    user: "${DOCKER_UID}:${DOCKER_UID}"
    build: 
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - ENV=test
        - FURY_AUTH
